version: '3'
services:

#  mongodb:
#    container_name: mongo.planez
#    image: percona/percona-server-mongodb:3.4
#    ports:
#     - "27017:27017"
#    volumes:
#     - ./data/mongo:/data/db
#    networks:
#     - planez

  planez:
    container_name: main.planez
    image: planez.co:5000/planez-ui:latest
#    depends_on:
#     - mongodb
    ports:
     - "9314:9314"
    networks:
     - planez

networks:
  planez:
