repos:
  - repo: local
    hooks:

      - id: check-fmt
        name: Check formatting
        entry: make check-format
        language: system
        pass_filenames: false
        always_run: true

      - id: mvn-compile
        name: Maven compile
        entry: mvn compile
        language: system
        pass_filenames: false
        always_run: true

