version: '3'
services:

  mongodb:
    container_name: quiz.mongo
    image: percona/percona-server-mongodb:3.4
    ports:
     - "27017:27017"
    volumes:
     - ./data/mongo:/data/db
    networks:
     - wcfc

networks:
  wcfc:
