apiVersion: v1
kind: Service
metadata:
  name: wcfc-quiz
  labels:
    run: wcfc-quiz
spec:
  type: NodePort
  ports:
  - port: 9314
    protocol: TCP
  selector:
    run: wcfc-quiz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcfc-quiz
  labels:
    app: wcfc-quiz
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: wcfc-quiz
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: wcfc-quiz
    spec:
      containers:
      - image: planez.co:5000/wcfc-quiz:latest
        imagePullPolicy: Never
        name: wcfc-quiz
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
